### ISSUE TITLE
Stacktrace: 0   undetected_chromedriver     

### ISSUE THREAD

**Issue by xiaoyichao** [acheong08/ChatGPT-Proxy#14] opened 2023-02-12 04:42 UTC
Stacktrace:
0   undetected_chromedriver             0x00000001030c4138 undetected_chromedriver + 4923704
1   undetected_chromedriver             0x000000010303c9d3 undetected_chromedriver + 4368851
2   undetected_chromedriver             0x0000000102c85787 undetected_chromedriver + 472967
3   undetected_chromedriver             0x0000000102cb6e79 undetected_chromedriver + 675449
4   undetected_chromedriver             0x0000000102cad8e2 undetected_chromedriver + 637154
5   undetected_chromedriver             0x0000000102cfc8a5 undetected_chromedriver + 960677
6   undetected_chromedriver             0x0000000102cf2d23 undetected_chromedriver + 920867
7   undetected_chromedriver             0x0000000102cb9a4b undetected_chromedriver + 686667
8   undetected_chromedriver             0x0000000102cbb044 undetected_chromedriver + 692292
9   undetected_chromedriver             0x000000010308f8fe undetected_chromedriver + 4708606
10  undetected_chromedriver             0x0000000103094e22 undetected_chromedriver + 4730402
11  undetected_chromedriver             0x000000010309d6bf undetected_chromedriver + 4765375
12  undetected_chromedriver             0x0000000103095e80 undetected_chromedriver + 4734592
13  undetected_chromedriver             0x0000000103066975 undetected_chromedriver + 4540789
14  undetected_chromedriver             0x00000001030b7e78 undetected_chromedriver + 4873848
15  undetected_chromedriver             0x00000001030b7ff5 undetected_chromedriver + 4874229
16  undetected_chromedriver             0x00000001030cc6de undetected_chromedriver + 4957918
17  libsystem_pthread.dylib             0x00007ff80bdc5259 _pthread_start + 125
18  libsystem_pthread.dylib             0x00007ff80bdc0c7b thread_start + 15

**Comment by acheong08** [comment] 2023-02-12 05:13
Duplicate of https://github.com/acheong08/ChatGPT-Proxy/issues/13

**Closed as completed by acheong08** 2023-02-12 05:13 UTC
