### ISSUE TITLE
发生异常: URLError <urlopen error EOF occurred in violation of protocol (_ssl.c:1129)> ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)  During handling of the above exception, another exception occurred:    File "/Users/xiaoyichao/projects/ChatGPT-Proxy/proxy.py", line 37, in <module>     ) = Cloudflare(proxy=PROXY).get_cf_cookies() urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:1129)>

### ISSUE THREAD

**Issue by xiaoyichao** [acheong08/ChatGPT-Proxy#15] opened 2023-02-12 04:44 UTC
发生异常: URLError
<urlopen error EOF occurred in violation of protocol (_ssl.c:1129)>
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

  File "/Users/xiaoyichao/projects/ChatGPT-Proxy/proxy.py", line 37, in <module>
    ) = Cloudflare(proxy=PROXY).get_cf_cookies()
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:1129)>

**Comment by acheong08** [comment] 2023-02-12 05:13
Duplicate of #13

**Closed as not planned** 2023-02-12 05:13 UTC
